/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import vac.Vistas.AdmCiudadano;

/**
 *
 * @author Ana y Guille
 */
public class ActualizaCiudadano extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizaCiudadano
     */
    public ActualizaCiudadano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTdni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTtelefono = new javax.swing.JTextField();
        jBsalir1 = new javax.swing.JButton();
        jBbuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCriesgo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCescencial = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdniActionPerformed(evt);
            }
        });
        jTdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdniKeyTyped(evt);
            }
        });
        getContentPane().add(jTdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, -1));

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 80, 20));

        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, -1));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, 20));

        jTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, -1));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("E-mail:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 20));

        jTmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTmailFocusLost(evt);
            }
        });
        getContentPane().add(jTmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, -1));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        jTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, -1));

        jBsalir1.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir1.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir1.setText("Salir");
        jBsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 100, 30));

        jBbuscar.setBackground(new java.awt.Color(153, 255, 204));
        jBbuscar.setText("Buscar");
        getContentPane().add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 100, 40));

        jLabel8.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Enf. de riesgo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 20));

        jCriesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0.Ninguna", "1. Enfermedad pulmonar", "2. Cardiopatías", "3. Diabetes", "4. Obesidad", "5. Transplante", "6. Inmuno deprimido", " " }));
        jCriesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriesgoActionPerformed(evt);
            }
        });
        getContentPane().add(jCriesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, -1));

        jLabel9.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Act. esencial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 20));

        jButton1.setText("Modificar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 20));

        jCescencial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ninguna", "1. Personal de Salud, Fuerzas de seguridad, Fuerzas Armadas.", "2. Autoridades superiores de los gobiernosres.", "3. Personal de los servicios de justicia de turno.", "4. Personal diplomático y consular extranjero. ", "5. Personas que deban asistir a otras con discapacidad. ", "6. Personas que deban atender una situación de fuerza mayor.", "7. Personas afectadas a la realización de servicios funerarios.", "8. Personas afectadas a la atención de comedoress.", "9. Personal que se desempeña en los servicios de comunicación.", "10. Personal afectado a obra pública.", "11. Supermercados y comercios minoristas de proximidad. ", "12. Industrias de alimentación", "13. Actividades distribución y comercialización agropecuaria y de pesca.", "14. Actividades de telecomunicaciones.", "15. Comercio exterior.", "16. Recolección, transporte y tratamiento de residuos sólidos urbanos.", "17. Mantenimiento de los servicios básicos.", "18. Transporte público de pasajeros.", "19. Reparto a domicilio.", "20. Servicios de lavandería.", "21. Servicios postales y de distribución de paquetería.", "22. Servicios esenciales de vigilancia, limpieza y guardia.", " " }));
        getContentPane().add(jCescencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 420, -1));

        jButton2.setText("Modificar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 20));

        jButton3.setText("Modificar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, 20));

        jButton4.setText("Modificar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, 20));

        jButton5.setText("Modificar");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, 20));

        jButton6.setText("Modificar");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 10));

        jLabel3.setFont(new java.awt.Font("Gulim", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Actualización de Datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 410, 40));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese DNI de la persona a actualizar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 340, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/transparent white.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoCiudadano.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniActionPerformed

    private void jTdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTdni.setText("");

        }
    }//GEN-LAST:event_jTdniKeyTyped

    private void jTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTnombre.setText("");

        }
    }//GEN-LAST:event_jTnombreKeyTyped

    private void jTapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellidoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTapellido.setText("");

        }
    }//GEN-LAST:event_jTapellidoKeyTyped
//    public boolean isEmail(String correo) {
//        Pattern pat = null;
//        Matcher mat = null;
//        pat = Pattern.compile("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
//        mat = pat.matcher(correo);
//
//        if (mat.find()) {
//            return true;
//        } else {
//            return false;
//        }
//
//    }
    private void jTmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTmailFocusLost
//        // TODO add your handling code here:
//       // if (isEmail(jTmail.getText())) {
//
//        } else {
//            JOptionPane.showMessageDialog(null, "El e-mail ingresado no es válido\nVuelva a ingresarlo");
//            jTmail.setText("");
//        }
    }//GEN-LAST:event_jTmailFocusLost

    private void jTtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelefonoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTtelefono.setText("");

        }
    }//GEN-LAST:event_jTtelefonoKeyTyped

    private void jCriesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCriesgoActionPerformed

    private void jBsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBsalir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCescencial;
    private javax.swing.JComboBox<String> jCriesgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTdni;
    private javax.swing.JTextField jTmail;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
