/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;


import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import vac.Data.CiudadanoData;
import vac.Vistas.AdmCiudadano;
import vac_Entidades.Ciudadano;

/**
 *
 * @author Ana y Guille
 */
public class ActualizaCiudadano extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizaCiudadano
     */
    public ActualizaCiudadano() {
        initComponents();
        jTnombre.setEnabled(false);
        jTapellido.setEnabled(false);
        jTmail.setEnabled(false);
        jTtelefono.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jCriesgo.setEnabled(false);
        jCescencial.setEnabled(false);
        jBmodificar.setEnabled(false);
        jBcancelar.setEnabled(false);

      
    }
    Ciudadano pers = new Ciudadano();
    CiudadanoData cd = new CiudadanoData();

    public void limpiar() {
        jTdni.setText("");
        jTnombre.setText("");
        jTapellido.setText("");
        jTmail.setText("");
        jTtelefono.setText("");
        jCriesgo.setSelectedIndex(0);
        jCescencial.setSelectedIndex(0);
        jactivo.setSelected(false);
        jinactivo.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTdni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBsalir1 = new javax.swing.JButton();
        jTmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTtelefono = new javax.swing.JTextField();
        jBmodificar = new javax.swing.JButton();
        jBbuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jCriesgo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCescencial = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jinactivo = new javax.swing.JCheckBox();
        jactivo = new javax.swing.JCheckBox();
        jBguardarCambios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdniActionPerformed(evt);
            }
        });
        jTdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdniKeyTyped(evt);
            }
        });
        getContentPane().add(jTdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, -1));

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 70, 20));

        jTnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, -1));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, 20));

        jTapellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, -1));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("E-mail:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 20));

        jBsalir1.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir1.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir1.setText("Salir");
        jBsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 160, 50));

        jTmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTmailFocusLost(evt);
            }
        });
        getContentPane().add(jTmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, -1));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        jTtelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, -1));

        jBmodificar.setBackground(new java.awt.Color(255, 255, 153));
        jBmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(0, 0, 0));
        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 120, 50));

        jBbuscar.setBackground(new java.awt.Color(153, 255, 204));
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 100, 40));

        jLabel8.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Enf. de riesgo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 20));

        jBcancelar.setBackground(new java.awt.Color(255, 51, 51));
        jBcancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBcancelar.setForeground(new java.awt.Color(0, 0, 0));
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 120, 50));

        jCriesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-Seleccione", "1-Ninguna", "2- Enfermedad pulmonar", "3- Cardiopatías", "4- Diabetes", "5- Obesidad", "6- Transplante", "7- Inmuno deprimido", " " }));
        jCriesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriesgoActionPerformed(evt);
            }
        });
        getContentPane().add(jCriesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, -1));

        jLabel9.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Act. esencial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 20));

        jCescencial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-Seleccione", "1-Ninguna", "2- Personal de Salud, Fuerzas de seguridad, Fuerzas Armadas.", "3- Autoridades superiores de los gobiernosres.", "4- Personal de los servicios de justicia de turno.", "5- Personal diplomático y consular extranjero. ", "6- Personas que deban asistir a otras con discapacidad. ", "7- Personas que deban atender una situación de fuerza mayor.", "8- Personas afectadas a la realización de servicios funerarios.", "9- Personas afectadas a la atención de comedoress.", "10- Personal de servicios de comunicación.", "11- Personal afectado a obra pública.", "12- Supermercados y comercios minoristas de proximidad. ", "13- Industrias de alimentación", "14- Actividades distribución y comercialización agropecuaria.", "15- Actividades de telecomunicaciones.", "16- Comercio exterior.", "17- Recolección, transporte y tratamiento de residuos.", "18- Mantenimiento de los servicios básicos.", "19- Transporte público de pasajeros.", "20- Reparto a domicilio.", "21- Servicios de lavandería.", "22- Servicios postales y de distribución de paquetería.", "23- Servicios esenciales de vigilancia, limpieza y guardia.", " ", " " }));
        getContentPane().add(jCescencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 420, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 10));

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 80, 20));

        jinactivo.setText("Inactivo");
        jinactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jinactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jactivo.setText("Activo");
        jactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 70, -1));

        jBguardarCambios.setBackground(new java.awt.Color(102, 204, 255));
        jBguardarCambios.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBguardarCambios.setForeground(new java.awt.Color(51, 51, 51));
        jBguardarCambios.setText("Guardar Cambios");
        jBguardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(jBguardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 160, 50));

        jLabel3.setFont(new java.awt.Font("Gulim", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Actualización de Datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 410, 40));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese DNI de la persona a actualizar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 340, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/transparent white.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoCiudadano.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniActionPerformed

    private void jTdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTdni.setText("");

        }
    }//GEN-LAST:event_jTdniKeyTyped

    private void jTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTnombre.setText("");

        }
    }//GEN-LAST:event_jTnombreKeyTyped

    private void jTapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellidoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTapellido.setText("");

        }
    }//GEN-LAST:event_jTapellidoKeyTyped
    public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);

        if (mat.find()) {
            return true;
        } else {
            return false;
        }

    }
    private void jTmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTmailFocusLost
//        // TODO add your handling code here:
//       // if (isEmail(jTmail.getText())) {
//
//        } else {
//            JOptionPane.showMessageDialog(null, "El e-mail ingresado no es válido\nVuelva a ingresarlo");
//            jTmail.setText("");
//        }
    }//GEN-LAST:event_jTmailFocusLost

    private void jTtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelefonoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTtelefono.setText("");

        }
    }//GEN-LAST:event_jTtelefonoKeyTyped

    private void jCriesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCriesgoActionPerformed

    private void jBsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalir1ActionPerformed

    private void jBguardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarCambiosActionPerformed
        // TODO add your handling code here:
        if (jTnombre.getText().isEmpty() || jTapellido.getText().isEmpty() || jTdni.getText().isEmpty() || jTmail.getText().isEmpty() || jTtelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los datos requeridos");

        } else {
            pers.setDni(Integer.parseInt(jTdni.getText()));
            pers.setNombre(jTnombre.getText());
            pers.setApellido(jTapellido.getText());
            pers.setEmail(jTmail.getText());
            pers.setCelular(jTtelefono.getText());
            pers.setPatologia(jCriesgo.getSelectedItem().toString());
            pers.setAmbtrabajo(jCescencial.getSelectedItem().toString());
            if(jactivo.isSelected()){
                pers.setEstado(true);
            }else{
                pers.setEstado(false);
            }

            cd.actualizarCiudadano(pers);

            limpiar();
            
            jTnombre.setEnabled(false);
        jTapellido.setEnabled(false);
        jTmail.setEnabled(false);
        jTtelefono.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jCriesgo.setEnabled(false);
        jCescencial.setEnabled(false);
        jBmodificar.setEnabled(true);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBbuscar.setEnabled(true);
        jBguardarCambios.setEnabled(false);
        jBmodificar.setEnabled(false);
            
        }

    }//GEN-LAST:event_jBguardarCambiosActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        pers = cd.buscarCiudadano(Integer.parseInt(jTdni.getText()));

        jTnombre.setText(pers.getNombre());
        jTapellido.setText(pers.getApellido());
        jTmail.setText(pers.getEmail());
        jTtelefono.setText(pers.getCelular());
        
        String cadena=pers.getAmbtrabajo();
        String[]frag=cadena.split("-");
        jCescencial.setSelectedIndex(Integer.parseInt(frag[0]));
        
        String cadenaPat=pers.getPatologia();
        String[]fragpat=cadenaPat.split("-");
        jCriesgo.setSelectedIndex(Integer.parseInt(fragpat[0]));

        
        if (pers.isEstado()) {
            jactivo.setSelected(true);
            jinactivo.setSelected(false);
        } else {
            jinactivo.setSelected(true);
            jactivo.setSelected(false);

        }

        jTnombre.setEnabled(false);
        jTapellido.setEnabled(false);
        jTmail.setEnabled(false);
        jTtelefono.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jCriesgo.setEnabled(false);
        jCescencial.setEnabled(false);
        jBmodificar.setEnabled(true);


    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
        jTnombre.setEnabled(true);
        jTapellido.setEnabled(true);
        jTmail.setEnabled(true);
        jTtelefono.setEnabled(true);
        jinactivo.setEnabled(true);
        jactivo.setEnabled(true);
        jBguardarCambios.setEnabled(true);
        jCriesgo.setEnabled(true);
        jCescencial.setEnabled(true);
        jBbuscar.setEnabled(false);
        jBcancelar.setEnabled(true);

        

    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jactivoActionPerformed
        // TODO add your handling code here:
        jinactivo.setSelected(false);
    }//GEN-LAST:event_jactivoActionPerformed

    private void jinactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinactivoActionPerformed
        // TODO add your handling code here:
        jactivo.setSelected(false);
    }//GEN-LAST:event_jinactivoActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
         jTnombre.setEnabled(false);
        jTapellido.setEnabled(false);
        jTmail.setEnabled(false);
        jTtelefono.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jCriesgo.setEnabled(false);
        jCescencial.setEnabled(false);
        jBbuscar.setEnabled(true);
        jBmodificar.setEnabled(false);
        jBcancelar.setEnabled(false);
        
    }//GEN-LAST:event_jBcancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardarCambios;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBsalir1;
    private javax.swing.JComboBox<String> jCescencial;
    private javax.swing.JComboBox<String> jCriesgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTdni;
    private javax.swing.JTextField jTmail;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelefono;
    private javax.swing.JCheckBox jactivo;
    private javax.swing.JCheckBox jinactivo;
    // End of variables declaration//GEN-END:variables
}
