/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vac.Data.LaboratorioData;
import vac_Entidades.Laboratorio;

/**
 *
 * @author Ana y Guille
 */
public class ActualizaLab extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizaLab
     */
    public ActualizaLab() {
        initComponents();
        jTcuit.setEnabled(false);
        jTnombre.setEnabled(false);
        jTdomicilio.setEnabled(false);
        jTpais.setEnabled(false);
        jBmodificar.setEnabled(false);
        jBcancelar.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jactivo.setEnabled(false);
        jinactivo.setEnabled(false);
        cargaCombo();
    }
public void limpiar(){
    jTcuit.setText("");
        jTnombre.setText("");
        jTdomicilio.setText("");
        jTpais.setText("");
        jinactivo.setSelected(false);
        jactivo.setSelected(false);
        jCLabs.setEnabled(true);
        jCLabs.setSelectedIndex(0);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTcuit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTpais = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCLabs = new javax.swing.JComboBox<>();
        jTdomicilio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jactivo = new javax.swing.JCheckBox();
        jinactivo = new javax.swing.JCheckBox();
        jBmodificar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBguardarCambios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Seleccione el Laboratorio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 20));

        jBbuscar.setBackground(new java.awt.Color(153, 255, 204));
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 100, 40));

        jBsalir.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 150, 50));

        jLabel4.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Actualización de Laboratorios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 510, 40));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("N° de CUIT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 20));

        jTcuit.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTcuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcuitKeyTyped(evt);
            }
        });
        getContentPane().add(jTcuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, -1));

        jLabel3.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, 20));

        jTnombre.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, -1));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Pais:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 50, 20));

        jTpais.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTpaisKeyTyped(evt);
            }
        });
        getContentPane().add(jTpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, -1));

        jLabel8.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Domicilio Comercial:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 20));

        jCLabs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jCLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLabsActionPerformed(evt);
            }
        });
        getContentPane().add(jCLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 230, -1));

        jTdomicilio.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jTdomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdomicilioKeyTyped(evt);
            }
        });
        getContentPane().add(jTdomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 310, -1));

        jLabel9.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 70, 20));

        jactivo.setText("Activo");
        jactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 70, -1));

        jinactivo.setText("Inactivo");
        jinactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jinactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jBmodificar.setBackground(new java.awt.Color(255, 255, 153));
        jBmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(0, 0, 0));
        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 120, 50));

        jBcancelar.setBackground(new java.awt.Color(255, 51, 51));
        jBcancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBcancelar.setForeground(new java.awt.Color(0, 0, 0));
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 120, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 10));

        jBguardarCambios.setBackground(new java.awt.Color(102, 204, 255));
        jBguardarCambios.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBguardarCambios.setForeground(new java.awt.Color(51, 51, 51));
        jBguardarCambios.setText("Guardar Cambios");
        jBguardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(jBguardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/transparent white.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoLaboratorio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        LaboratorioData ld = new LaboratorioData();
        Laboratorio lab = new Laboratorio();
        lab = ld.buscarLaboratorio(jCLabs.getSelectedItem().toString());

        jTcuit.setText(lab.getCuit());
        jTnombre.setText(lab.getNomLab());
        jTdomicilio.setText(lab.getDomCom());
        jTpais.setText(lab.getPais());

        if (lab.isEstado()) {
            jactivo.setSelected(true);
            jinactivo.setSelected(false);
        } else {
            jinactivo.setSelected(true);
            jactivo.setSelected(false);

        }

        jTcuit.setEnabled(false);
        jTnombre.setEnabled(false);
        jTdomicilio.setEnabled(false);
        jTpais.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jBmodificar.setEnabled(true);
        jBcancelar.setEnabled(true);
        jBbuscar.setEnabled(true);


    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jTcuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcuitKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {

            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTcuit.setText("");

        }
    }//GEN-LAST:event_jTcuitKeyTyped

    private void jTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTnombre.setText("");

        }
    }//GEN-LAST:event_jTnombreKeyTyped

    private void jTpaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpaisKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite texto \nVuelva a ingresarlo");
            jTpais.setText("");

        }
    }//GEN-LAST:event_jTpaisKeyTyped

    private void jTdomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdomicilioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE) && (car < '0' || car > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite texto \nVuelva a ingresarlo");
            jTpais.setText("");

        }
    }//GEN-LAST:event_jTdomicilioKeyTyped

    private void jactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jactivoActionPerformed
        // TODO add your handling code here:
        jinactivo.setSelected(false);
    }//GEN-LAST:event_jactivoActionPerformed

    private void jinactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinactivoActionPerformed
        // TODO add your handling code here:
        jactivo.setSelected(false);
    }//GEN-LAST:event_jinactivoActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
        jTcuit.setEnabled(true);
        jTnombre.setEnabled(true);
        jTdomicilio.setEnabled(true);
        jTpais.setEnabled(true);
        jinactivo.setEnabled(true);
        jactivo.setEnabled(true);
        jBguardarCambios.setEnabled(true);
        jBmodificar.setEnabled(false);
        jBcancelar.setEnabled(true);
        jBbuscar.setEnabled(false);
        jCLabs.setEnabled(false);


    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        jTcuit.setEnabled(false);
        jTnombre.setEnabled(false);
        jTdomicilio.setEnabled(false);
        jTpais.setEnabled(false);
        jinactivo.setEnabled(false);
        jactivo.setEnabled(false);
        jBguardarCambios.setEnabled(false);
        jBmodificar.setEnabled(false);
        jBcancelar.setEnabled(true);
        jBbuscar.setEnabled(true);
        jCLabs.setEnabled(true);

        limpiar();
        

    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBguardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarCambiosActionPerformed
        // TODO add your handling code here:
        Laboratorio lab=new Laboratorio();
        LaboratorioData ld=new LaboratorioData();
        
        if (jTnombre.getText().isEmpty() || jTnombre.getText().isEmpty() || jTcuit.getText().isEmpty() || jTdomicilio.getText().isEmpty() || jTdomicilio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los datos requeridos");

        } else {
            lab.setCuit(jTcuit.getText());
            lab.setNomLab(jTnombre.getText());
            lab.setPais(jTpais.getText());
            lab.setDomCom(jTdomicilio.getText());
            lab.setEstado(true);
            ld.actualizarLaboratorio(lab);

                    limpiar();
                    jBbuscar.setEnabled(true);
        } 
    }//GEN-LAST:event_jBguardarCambiosActionPerformed

    private void jCLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLabsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardarCambios;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jCLabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTcuit;
    private javax.swing.JTextField jTdomicilio;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTpais;
    private javax.swing.JCheckBox jactivo;
    private javax.swing.JCheckBox jinactivo;
    // End of variables declaration//GEN-END:variables
 private void cargaCombo() {
        LaboratorioData ld = new LaboratorioData();
        ArrayList<String> lista = new ArrayList<>();
        lista = ld.listarLab();

        for (String elemento : lista) {

            jCLabs.addItem(elemento);

        }
    }

}
