/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import vac.Data.LaboratorioData;
import vac_Entidades.Laboratorio;

/**
 *
 * @author Ana y Guille
 */
public class AdmLaboratorio extends javax.swing.JInternalFrame {

    Laboratorio lab = new Laboratorio();
    LaboratorioData ld = new LaboratorioData();

    public AdmLaboratorio() {
        initComponents();
    }

    public void limpiar() {
        jTcuit.setText("");
        jTnombre.setText("");
        jTdomicilio.setText("");
        jTdomicilio.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBeliminar = new javax.swing.JButton();
        jTdniEliminar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTcuit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTcuitEliminar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBeliminarLab = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBregistrar = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jTpais = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTdomicilio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jBeliminar.setBackground(new java.awt.Color(204, 0, 51));
        jBeliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBeliminar.setText("Eliminar inscripto");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ingrese DNI de la persona a eliminar:");

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Registro de Laboratorios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 420, 40));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("N° de CUIT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 100, 20));

        jTcuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcuitKeyTyped(evt);
            }
        });
        getContentPane().add(jTcuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 240, -1));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 70, 20));

        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 240, -1));

        jTcuitEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcuitEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jTcuitEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 180, -1));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ingrese CUIT de Laboratorio:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 250, 20));

        jBeliminarLab.setBackground(new java.awt.Color(204, 0, 51));
        jBeliminarLab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBeliminarLab.setForeground(new java.awt.Color(255, 255, 255));
        jBeliminarLab.setText("Eliminar Laboratorio");
        getContentPane().add(jBeliminarLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 180, 50));

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Pais:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 50, 20));

        jBsalir.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 150, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/light-gray-concrete-wall.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 700, 100));

        jBregistrar.setBackground(new java.awt.Color(102, 204, 255));
        jBregistrar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBregistrar.setForeground(new java.awt.Color(51, 51, 51));
        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 150, 50));

        jBlimpiar.setBackground(new java.awt.Color(153, 255, 153));
        jBlimpiar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBlimpiar.setForeground(new java.awt.Color(51, 51, 51));
        jBlimpiar.setText("Limpiar campos");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 150, 50));

        jBactualizar.setBackground(new java.awt.Color(255, 255, 153));
        jBactualizar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBactualizar.setForeground(new java.awt.Color(51, 51, 51));
        jBactualizar.setText("Actualizar datos");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 150, 50));

        jTpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTpaisKeyTyped(evt);
            }
        });
        getContentPane().add(jTpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 240, -1));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Domicilio Comercial:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 180, 20));

        jTdomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdomicilioKeyTyped(evt);
            }
        });
        getContentPane().add(jTdomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 310, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/transparent white.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 260, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoLaboratorio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcuitKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {

            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTcuit.setText("");

        }
    }//GEN-LAST:event_jTcuitKeyTyped

    private void jTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTnombre.setText("");

        }
    }//GEN-LAST:event_jTnombreKeyTyped

    private void jTpaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpaisKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite texto \nVuelva a ingresarlo");
            jTpais.setText("");

        }
    }//GEN-LAST:event_jTpaisKeyTyped

    private void jTdomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdomicilioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE) || (car < '0' || car > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite texto \nVuelva a ingresarlo");
            jTpais.setText("");

        }
    }//GEN-LAST:event_jTdomicilioKeyTyped

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        // TODO add your handling code here:
        if (jTnombre.getText().isEmpty() || jTnombre.getText().isEmpty() || jTcuit.getText().isEmpty() || jTdomicilio.getText().isEmpty() || jTdomicilio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los datos requeridos");

        } else {
            //instanciar objeto lab
            
                    //ejecutar metodo registarLab()

                    limpiar();
        }

    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Para actualizar debe completar todos los campos con los datos del laboratorio a mofificar y luego presionar ACTUALIZAR");
        if (jTnombre.getText().isEmpty() || jTnombre.getText().isEmpty() || jTcuit.getText().isEmpty() || jTdomicilio.getText().isEmpty() || jTdomicilio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los datos requeridos");

        } else {
            //instanciar objeto lab
            

            limpiar();
        }
    }//GEN-LAST:event_jBactualizarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        if (jTcuitEliminar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un DNI en el campo Eliminar Ciudadano");
        } else {
            //capturar cuit
            jTdniEliminar.setText("");
        }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jTcuitEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcuitEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcuitEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBeliminarLab;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTcuit;
    private javax.swing.JTextField jTcuitEliminar;
    private javax.swing.JTextField jTdniEliminar;
    private javax.swing.JTextField jTdomicilio;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTpais;
    // End of variables declaration//GEN-END:variables
}
