/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vac.Data.LaboratorioData;
import vac.Data.VacunaData;
import vac_Entidades.Laboratorio;
import vac_Entidades.Vacuna;

/**
 *
 * @author Ana y Guille
 */
public class AdmVacuna extends javax.swing.JInternalFrame {

    public Laboratorio lab = new Laboratorio();
    public LaboratorioData ld = new LaboratorioData();
    public Vacuna vac = new Vacuna();
    public VacunaData vd = new VacunaData();

    public AdmVacuna() {
        initComponents();
        jDateChooser1.setMinSelectableDate(Date.valueOf(LocalDate.of(2024, 10, 15)));
        cargaCombo();

        //Seteo de Date
//          Seteo de DateChooser para dosis de refuerzo
//        jDateChooser1.setMinSelectableDate(fechaColocada+28);
//        jDateChooser1.setMaxSelectableDate(fechaColocada+56);
    }

    public void limpiar() {
        jTnoDosis.setText("");
        jCvacunas.setSelectedIndex(0);
        jCmedida.setSelectedIndex(0);
        jDateChooser1.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTeliminaDosis = new javax.swing.JTextField();
        jBregistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jBvencidas = new javax.swing.JButton();
        jBeliminaDosis = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTnoDosis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCvacunas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCmedida = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLfondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBackground(new java.awt.Color(102, 102, 102));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 0, 0));

        jTeliminaDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeliminaDosisActionPerformed(evt);
            }
        });
        getContentPane().add(jTeliminaDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 180, -1));

        jBregistrar.setBackground(new java.awt.Color(102, 204, 255));
        jBregistrar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBregistrar.setForeground(new java.awt.Color(51, 51, 51));
        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 150, 50));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ingrese N° de Serie de Dosis:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 250, 20));

        jBsalir.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 150, 50));

        jBvencidas.setBackground(new java.awt.Color(255, 255, 153));
        jBvencidas.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBvencidas.setForeground(new java.awt.Color(51, 51, 51));
        jBvencidas.setText("Eliminar Vencidas");
        jBvencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvencidasActionPerformed(evt);
            }
        });
        getContentPane().add(jBvencidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 350, -1, 50));

        jBeliminaDosis.setBackground(new java.awt.Color(204, 0, 51));
        jBeliminaDosis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBeliminaDosis.setForeground(new java.awt.Color(255, 255, 255));
        jBeliminaDosis.setText("Baja Vacuna");
        jBeliminaDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminaDosisActionPerformed(evt);
            }
        });
        getContentPane().add(jBeliminaDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 180, 50));

        jBlimpiar.setBackground(new java.awt.Color(153, 255, 153));
        jBlimpiar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBlimpiar.setForeground(new java.awt.Color(51, 51, 51));
        jBlimpiar.setText("Limpiar campos");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 150, 50));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("N° Dosis:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 100, 20));

        jTnoDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnoDosisActionPerformed(evt);
            }
        });
        jTnoDosis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnoDosisKeyTyped(evt);
            }
        });
        getContentPane().add(jTnoDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 240, -1));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Fecha caducidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 170, 20));

        jLabel3.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Registro de Vacunas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 360, 40));

        jCvacunas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        getContentPane().add(jCvacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 240, -1));

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Marca:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 70, 20));

        jCmedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Seleccione...", "0.3", "0.5", "0.9" }));
        getContentPane().add(jCmedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 240, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 230, 240, -1));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Medida(ml):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/light-gray-concrete-wall.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 700, 90));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondovacuna.jpg"))); // NOI18N
        getContentPane().add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBeliminaDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminaDosisActionPerformed
        // TODO add your handling code here:
        vd.eliminarVacuna(Integer.parseInt(jTeliminaDosis.getText()));
        jTeliminaDosis.setText("");
        JOptionPane.showMessageDialog(null, "Eliminó la vacuna ingresada.");
    }//GEN-LAST:event_jBeliminaDosisActionPerformed

    private void jBvencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvencidasActionPerformed
        // TODO add your handling code here:
        VacunaData vd = new VacunaData();
        LocalDate hoy = LocalDate.now();
        ArrayList<Vacuna> vac = new ArrayList();
        vac = vd.buscarvacuna();

        int i = 0;
        for (Vacuna vacuna : vac) {
            if (vacuna.getFechaCaduca().isBefore(hoy) ) {

                vd.eliminarVacuna(vacuna.getIdVacuna());

                i++;
            }
        }
        if (i > 0) {
            JOptionPane.showMessageDialog(null, "Vencieron " + i + " vacunas, se retiran del programa");
        } else {
            JOptionPane.showMessageDialog(null, "No se detectaron vacunas vencidas.");
        }

    }//GEN-LAST:event_jBvencidasActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        // TODO add your handling code here:
        if (jTnoDosis.getText().isEmpty() || jDateChooser1.getDate() == null || jCvacunas.getSelectedIndex() == 0 || jCmedida.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los datos requeridos");

        } else {
            vac.setMarca(jCvacunas.getSelectedItem().toString());
            vac.setMedida(Double.parseDouble((String) jCmedida.getSelectedItem()));
            vac.setEstado(true);
            vac.setNoSerieDosis((jTnoDosis.getText()));
            vac.setColocada(0 == 1);
            vac.setFechaCaduca(jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());

            vd.ingresarVacuna(vac);
            limpiar();

        }
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jTeliminaDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeliminaDosisActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTeliminaDosisActionPerformed

    private void jTnoDosisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnoDosisKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE) && (car < 'A' || car > 'z') && (car < 45 || car > 45)) {

            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTnoDosis.setText("");

        }
    }//GEN-LAST:event_jTnoDosisKeyTyped

    private void jTnoDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnoDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnoDosisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminaDosis;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jBvencidas;
    private javax.swing.JComboBox<String> jCmedida;
    private javax.swing.JComboBox<String> jCvacunas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JTextField jTeliminaDosis;
    private javax.swing.JTextField jTnoDosis;
    // End of variables declaration//GEN-END:variables

    private void cargaCombo() {

        ArrayList<String> lista = new ArrayList<>();
        lista = ld.listarLab();

        for (String elemento : lista) {

            jCvacunas.addItem(elemento);

        }
    }
}
