/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import javax.swing.table.DefaultTableModel;
import vac.Data.ConsultaData;
import vac_Entidades.CitaVacunacion;

/**
 *
 * @author krist
 */
public class listaDiarias extends javax.swing.JInternalFrame {

    /**
     * Creates new form listaDiarias
     */
    public listaDiarias() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTdosis = new javax.swing.JTable();
        jCvacunatorio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBsalir1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTdosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "centroVacunacion", "DosisAplicadas"
            }
        ));
        getContentPane().add(jTdosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 590, 110));

        jCvacunatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1- Cruz Roja Central", "2- Centro Cultural Leo Messi", "3- Club Social y Deportivo Cebollitas", "4-", "5- Escuela Normal N°10" }));
        jCvacunatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCvacunatorioItemStateChanged(evt);
            }
        });
        jCvacunatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCvacunatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jCvacunatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 280, -1));

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Vacunatorio:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 30));

        jLabel6.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Listas Diarias");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 240, 40));

        jBsalir1.setBackground(new java.awt.Color(255, 153, 153));
        jBsalir1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBsalir1.setForeground(new java.awt.Color(51, 51, 51));
        jBsalir1.setText("Salir");
        jBsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoCiudadano.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCvacunatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCvacunatorioActionPerformed
        // TODO add your handling code here:
        
        ConsultaData CONS = new ConsultaData();
//        
//        DefaultTableModel tabla = new DefaultTableModel();
//        
//        tabla.addColumn("Centro de Vacunación");
//        tabla.addColumn("Dosis Aplicadas");
//        jCvacunatorio.setModel(tabla);
//        
        CONS.listarCitas();
        
    }//GEN-LAST:event_jCvacunatorioActionPerformed

    private void jCvacunatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCvacunatorioItemStateChanged
        // TODO add your handling code here:
        
//        ConsultaData CONS = new ConsultaData();
//        
//        String centro = (String) jCvacunatorio.getSelectedItem();
//        
//        if (centro.equals("1-Cruz Roja Central")) {
//            
//            CONS.listarCitas();
//        }
    }//GEN-LAST:event_jCvacunatorioItemStateChanged

    private void jBsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir1;
    private javax.swing.JComboBox<String> jCvacunatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTable jTdosis;
    // End of variables declaration//GEN-END:variables
}
