/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import javax.swing.table.DefaultTableModel;
import vac.Data.ConsultaData;
import vac_Entidades.CitaVacunacion;

/**
 *
 * @author krist
 */
public class listaDiarias extends javax.swing.JInternalFrame {

    /**
     * Creates new form listaDiarias
     */
    public listaDiarias() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTdosis = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jCvacunatorio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTdosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "centroVacunacion", "DosisAplicadas"
            }
        ));
        getContentPane().add(jTdosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 590, 340));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("                            Lista Diaria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 370, -1));

        jCvacunatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1- Cruz Roja Central", "2- Centro Cultural Leo Messi", "3- Club Social y Deportivo Cebollitas", "5- Escuela Normal N°10" }));
        jCvacunatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCvacunatorioItemStateChanged(evt);
            }
        });
        jCvacunatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCvacunatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jCvacunatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 280, -1));

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Vacunatorio:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoCiudadano.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCvacunatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCvacunatorioActionPerformed
        // TODO add your handling code here:
        
        ConsultaData CONS = new ConsultaData();
//        
//        DefaultTableModel tabla = new DefaultTableModel();
//        
//        tabla.addColumn("Centro de Vacunación");
//        tabla.addColumn("Dosis Aplicadas");
//        jCvacunatorio.setModel(tabla);
//        
        CONS.listarCitas();
        
    }//GEN-LAST:event_jCvacunatorioActionPerformed

    private void jCvacunatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCvacunatorioItemStateChanged
        // TODO add your handling code here:
        
//        ConsultaData CONS = new ConsultaData();
//        
//        String centro = (String) jCvacunatorio.getSelectedItem();
//        
//        if (centro.equals("1-Cruz Roja Central")) {
//            
//            CONS.listarCitas();
//        }
    }//GEN-LAST:event_jCvacunatorioItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCvacunatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTable jTdosis;
    // End of variables declaration//GEN-END:variables
}
