/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vac.Vistas;

import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import vac.Data.CitaData;
import vac.Data.CiudadanoData;
import vac.Data.VacunaData;
import vac_Entidades.CitaVacunacion;
import vac_Entidades.Ciudadano;
import vac_Entidades.Vacuna;

/**
 *
 * @author Ana y Guille
 */
public class PosponerCancelar extends javax.swing.JInternalFrame {

    /**
     * Creates new form PosponerCancelar
     */
    public PosponerCancelar() {
        initComponents();
        jChorario.setEnabled(false);
        jCvacunatorio.setEnabled(false);
        jDateChooser1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTdniPosCan = new javax.swing.JTextField();
        jBbuscarTurno = new javax.swing.JButton();
        jTnomApe = new javax.swing.JTextField();
        jTdatosTurno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jBcancelarTurno = new javax.swing.JButton();
        jBposponerTurno1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jChorario = new javax.swing.JComboBox<>();
        jCvacunatorio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBguardarPos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Posponer y Cancelar Turno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 480, 40));

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("DNI Persona:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 20));

        jTdniPosCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdniPosCanActionPerformed(evt);
            }
        });
        jTdniPosCan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdniPosCanKeyTyped(evt);
            }
        });
        getContentPane().add(jTdniPosCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, -1));

        jBbuscarTurno.setBackground(new java.awt.Color(153, 255, 204));
        jBbuscarTurno.setText("Buscar Turno");
        jBbuscarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(jBbuscarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 130, 40));

        jTnomApe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTnomApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnomApeKeyTyped(evt);
            }
        });
        getContentPane().add(jTnomApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 260, -1));
        getContentPane().add(jTdatosTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 650, -1));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre y apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 160, 20));

        jBsalir.setBackground(new java.awt.Color(255, 102, 102));
        jBsalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(0, 0, 0));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 120, 50));

        jBcancelarTurno.setBackground(new java.awt.Color(255, 51, 51));
        jBcancelarTurno.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBcancelarTurno.setForeground(new java.awt.Color(51, 51, 51));
        jBcancelarTurno.setText("Cancelar Turno");
        jBcancelarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 50));

        jBposponerTurno1.setBackground(new java.awt.Color(255, 255, 153));
        jBposponerTurno1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBposponerTurno1.setForeground(new java.awt.Color(51, 51, 51));
        jBposponerTurno1.setText("Posponer turno ");
        jBposponerTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBposponerTurno1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBposponerTurno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 220, 50));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 190, -1));

        jChorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " ", "10:00 a 10:30", "10:30 a 11:00", "11:00 a 11:30", "11:30 a 12:00", "12:00 a 12:30", "12:30 a 13:00", "13:00 a 13:30", "13:30 a 14:00", "14:00 a 14:30", "14:30 a 15:00", "15:00 a 15:30", "15:30 a 16:00" }));
        getContentPane().add(jChorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 190, -1));

        jCvacunatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1- Cruz Roja Central", "2- Centro Cultural Leo Messi", "3- Club Social y Deportivo Cebollitas", "5- Escuela Normal N°10" }));
        getContentPane().add(jCvacunatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 190, -1));

        jLabel10.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Fecha Turno:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 20));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Franja Horaria:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 20));

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Vacunatorio:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, 20));

        jBguardarPos.setBackground(new java.awt.Color(102, 204, 255));
        jBguardarPos.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBguardarPos.setForeground(new java.awt.Color(51, 51, 51));
        jBguardarPos.setText("Guardar Cambios");
        jBguardarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarPosActionPerformed(evt);
            }
        });
        getContentPane().add(jBguardarPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoCita.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTdniPosCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdniPosCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdniPosCanActionPerformed

    private void jTdniPosCanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdniPosCanKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite números \nVuelva a ingresarlo");
            jTdniPosCan.setText("");

        }
    }//GEN-LAST:event_jTdniPosCanKeyTyped

    private void jBbuscarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarTurnoActionPerformed
        // TODO add your handling code here:
        Ciudadano pers = new Ciudadano();
        CiudadanoData cd = new CiudadanoData();
        Vacuna vac = new Vacuna();
        VacunaData vd = new VacunaData();
        CitaData cdata = new CitaData();
        CitaVacunacion cv = new CitaVacunacion();
        try {
            pers = cd.buscarCiudadano(Integer.parseInt(jTdniPosCan.getText()));
            cv = cdata.buscarCitaCancel(pers);

            if (pers.getApellido() == null || cv.getPersona().getApellido() == null) {
                JOptionPane.showMessageDialog(null, "No hay turnos agendados para la persona solicitada o la persona no ha sido ingresada a la Base de Datos");
                jTdniPosCan.setText("");
            } else {
                jTnomApe.setText(pers.getNombre() + " " + pers.getApellido());
            }
            jTdatosTurno.setText(cv.getFechaHoraCita() + " " + cv.getCentroVacunacion());
        } catch (NullPointerException nex) {
            JOptionPane.showMessageDialog(null, "No hay un turno activo para la persona solicitada");
            jTdniPosCan.setText("");
        }
    }//GEN-LAST:event_jBbuscarTurnoActionPerformed

    private void jTnomApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnomApeKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < 65 || car > 90) && (car < 96 || car > 122) && (car < 128 || car > 183) && (car != (char) KeyEvent.VK_BACK_SPACE) && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Este campo solo admite letras \nVuelva a ingresarlo");
            jTnomApe.setText("");

        }
    }//GEN-LAST:event_jTnomApeKeyTyped

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBcancelarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarTurnoActionPerformed
        // TODO add your handling code here:
        Ciudadano pers = new Ciudadano();
        CiudadanoData cd = new CiudadanoData();
        Vacuna vac = new Vacuna();
        VacunaData vd = new VacunaData();
        CitaData cdata = new CitaData();
        CitaVacunacion cv = new CitaVacunacion();

        pers = cd.buscarCiudadano(Integer.parseInt(jTdniPosCan.getText()));
        cv = cdata.buscarCitaCancel(pers);

        cdata.cancelaCita(cv);


    }//GEN-LAST:event_jBcancelarTurnoActionPerformed

    private void jBposponerTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBposponerTurno1ActionPerformed
        // TODO add your handling code here:
        jChorario.setEnabled(true);
        jCvacunatorio.setEnabled(true);
        jDateChooser1.setEnabled(true);
        // cdata.posponerCita(cv);
    }//GEN-LAST:event_jBposponerTurno1ActionPerformed

    private void jBguardarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarPosActionPerformed
        // TODO add your handling code here:

        Ciudadano pers = new Ciudadano();
        CiudadanoData cd = new CiudadanoData();
        LocalDate fecha = null;
        Vacuna vac = new Vacuna();
        VacunaData vd = new VacunaData();
        CitaData cdata = new CitaData();
        CitaVacunacion cv = new CitaVacunacion();

        pers = cd.buscarCiudadano(Integer.parseInt(jTdniPosCan.getText()));
        cv = cdata.buscarCita(pers);
        
        cv.setCentroVacunacion(jCvacunatorio.getSelectedItem().toString());

        cv.setFechaHoraCita(jDateChooser1.getDate().toString() + "- " + jChorario.getSelectedItem().toString());
        
        cdata.posponerCita(cv);
       

        jTnomApe.setEnabled(false);

        jBguardarPos.setEnabled(false);

        jDateChooser1.setEnabled(false);
        jCvacunatorio.setEnabled(false);
        jChorario.setEnabled(false);
        jBbuscarTurno.setEnabled(true);

    }//GEN-LAST:event_jBguardarPosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscarTurno;
    private javax.swing.JButton jBcancelarTurno;
    private javax.swing.JButton jBguardarPos;
    private javax.swing.JButton jBposponerTurno1;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jChorario;
    private javax.swing.JComboBox<String> jCvacunatorio;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTdatosTurno;
    private javax.swing.JTextField jTdniPosCan;
    private javax.swing.JTextField jTnomApe;
    // End of variables declaration//GEN-END:variables
}
